### PR TITLE
design a little changed / search logic changed / better user experienc…

### PR DESCRIPTION
**Pull request by Sky-De**
i did not redesign all your app, because it required major structure change, what i did ?
1. added some new css to index.css file and commented some of your css - it looks better already
2.gitHub btn now in in header 
3.added search suggestion for better user experieance
4. added 1 and 2 to your not unique questions
and this is final apperance

**mobile**
1.

mob1

2.

mob2

3.

mob3

**desktop**
1.
desk 1

if you got any question feel free to ask, otherwise merge this commit 
thanks

### CODE REVIEW

**Comment by scorcism** [comment]
Hey @Sky-De you did a really great job,
You are just awesome

There is a conflict, please fix it. ig you should perform **git pull** to align with the main.
1. There was a new merge where it uses **hashmap** to fetch answers. You should check that too
2. You can also check for [this](https://imgur.com/ffEvyeY.png)

rest everything's fine

**Comment by scorcism** [comment]
hey @Sky-De,

fix the merge conflict so i can merge to main branch

**Comment by Sky-De** [comment]
@scorcism conflicts had been resolved 
thanks for your kind feedback
i hope you enjoy that
at last but not least i highly recommend you to follow a solid approach to code for more scaleabe and maintainable app

**Comment by scorcism** [comment]
@Sky-De great and thanks for the recommendation bro. Will follow sure

**Pull request merged**
